In [35]:
import pandas as pd
import numpy as np

In [36]:
df = pd.read_csv(r"C:\Users\m7897\Downloads\healthcare_dataset.csv")

In [37]:
df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

In [38]:
df.tail()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [39]:
df.columns

Index(['Name', 'Age', 'Gender', 'Blood Type', 'Medical Condition',
       'Date of Admission', 'Doctor', 'Hospital', 'Insurance Provider',
       'Billing Amount', 'Room Number', 'Admission Type', 'Discharge Date',
       'Medication', 'Test Results'],
      dtype='str')

In [40]:
df.shape

(55500, 15)

In [41]:
df.isnull().sum()

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

In [42]:
df.duplicated().sum()

np.int64(534)

In [43]:
df.drop_duplicates()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [44]:
df["Medical Condition"].isnull().sum()

np.int64(0)

In [45]:
df["Medical Condition"] = df["Medical Condition"].fillna("Unknown")

In [46]:
df["Billing Amount"] = df["Billing Amount"].fillna(df["Billing Amount"].median())

In [47]:
df["Date of Admission"] = pd.to_datetime(df["Date of Admission"])

In [48]:
df["Admission Year"] = df["Date of Admission"].dt.year
df["Admission Month"] = df["Date of Admission"].dt.month
df["Admission Date"] = df["Date of Admission"].dt.date

In [49]:
df["Gender"] = df["Gender"].str.strip().str.title()
df["Medical Condition"] = df["Medical Condition"].str.strip().str.title()
df["Admission Type"] = df["Admission Type"].str.strip().str.title()

In [50]:
def categorize_urgency(admission_type):
    if admission_type == "Emergency":
        return "Emergency"
    elif admission_type == "Urgent":
        return "Urgent"
    else:
        return "Elective"

df["Urgency"] = df["Admission Type"].apply(categorize_urgency)

In [51]:
print(df["Urgency"].value_counts())

Urgency
Elective     18655
Urgent       18576
Emergency    18269
Name: count, dtype: int64

In [52]:
print(df["Gender"].value_counts())

Gender
Male      27774
Female    27726
Name: count, dtype: int64

In [53]:
print(df["Gender"].value_counts(normalize=True) * 100)

Gender
Male      50.043243
Female    49.956757
Name: proportion, dtype: float64

In [54]:
print(df["Age"].describe())

count    55500.000000
mean        51.539459
std         19.602454
min         13.000000
25%         35.000000
50%         52.000000
75%         68.000000
max         89.000000
Name: Age, dtype: float64

In [55]:
bins = [0, 18, 35, 50, 65, 100]
labels = ["0-18", "19-35", "36-50", "51-65", "66+"]

df["Age Group"] = pd.cut(
    df["Age"],
    bins=bins,
    labels=labels
)

In [56]:
df["Age Group"].value_counts()

Age Group
66+      16250
19-35    13644
51-65    12417
36-50    12301
0-18       888
Name: count, dtype: int64

In [57]:
df["Billing Amount"].describe()

count    55500.000000
mean     25539.316097
std      14211.454431
min      -2008.492140
25%      13241.224652
50%      25538.069376
75%      37820.508436
max      52764.276736
Name: Billing Amount, dtype: float64

In [58]:
print("Mean:", df["Billing Amount"].mean())
print("Median:", df["Billing Amount"].median())
print("Minimum:", df["Billing Amount"].min())
print("Maximum:", df["Billing Amount"].max())
print("Standard Deviation:", df["Billing Amount"].std())

Mean: 25539.316097211795
Median: 25538.069375965664
Minimum: -2008.4921398591305
Maximum: 52764.276736469175
Standard Deviation: 14211.454430864413

In [59]:
df["Discharge Date"] = pd.to_datetime(
    df["Discharge Date"],
    errors="coerce"
)

In [60]:
df["Stay Days"] = (
    df["Discharge Date"] - df["Date of Admission"]
).dt.days

In [61]:
df["Stay Days"].describe()

count    55500.000000
mean        15.509009
std          8.659600
min          1.000000
25%          8.000000
50%         15.000000
75%         23.000000
max         30.000000
Name: Stay Days, dtype: float64

In [62]:
df["Medical Condition"].value_counts()

Medical Condition
Arthritis       9308
Diabetes        9304
Hypertension    9245
Obesity         9231
Cancer          9227
Asthma          9185
Name: count, dtype: int64

In [63]:
gender_condition = pd.crosstab(
    df["Medical Condition"],
    df["Gender"]
)

print(gender_condition)

Gender             Female  Male
Medical Condition
Arthritis            4686  4622
Asthma               4553  4632
Cancer               4602  4625
Diabetes             4651  4653
Hypertension         4612  4633
Obesity              4622  4609

In [64]:
age_condition = pd.crosstab(
    df["Medical Condition"],
    df["Age Group"]
)

print(age_condition)

Age Group          0-18  19-35  36-50  51-65   66+
Medical Condition
Arthritis           150   2279   2084   2047  2748
Asthma              150   2289   2009   1998  2739
Cancer              146   2288   2011   2072  2710
Diabetes            140   2246   2115   2107  2696
Hypertension        143   2252   2035   2071  2744
Obesity             159   2290   2047   2122  2613

In [65]:
stay_condition = df.groupby(
    "Medical Condition"
)["Stay Days"].mean()

print(stay_condition)

Medical Condition
Arthritis       15.517404
Asthma          15.696570
Cancer          15.495827
Diabetes        15.422936
Hypertension    15.458626
Obesity         15.464305
Name: Stay Days, dtype: float64

In [66]:
df.to_csv("cleaned_healthcare_dataset.csv", index=False)